variables:
  GOPATH: '$(system.defaultWorkingDirectory)/gopath' # Go workspace path
  GOBIN:  '$(GOPATH)/bin' # Go binaries path

trigger: none

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: GoTool@0
  displayName: 'Use latest Go '
  inputs:
    version: '1.16.3'
    
- task: Go@0
  displayName: 'Get CLAAT'
  inputs:    
    command: 'custom'
    customCommand: 'install'
    arguments: 'github.com/googlecodelabs/tools/claat@latest'
    
- task: CmdLine@2
  displayName: 'Copy markdown files and attachments to public folder'
  inputs:
    script: |
      mkdir codelabs 

- task: CmdLine@2
  displayName: 'Compile markdown files'
  inputs:
    script: |
      for i in `find ALM SpecFlow -name "*.md" -type f`; do
        $(GOBIN)/claat export "$i" -o codelabs
        echo "$i"
      done
      tree -a codelabs 

