trigger: none

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: GoTool@0
  displayName: 'Use latest Go '
  inputs:
    version: '1.16.3'

- task: Go@0
  displayName: 'Get CLAAT'
  inputs:
    command: 'get'
    arguments: '-v github.com/googlecodelabs/tools/claat'
    
- task: CmdLine@2
  displayName: 'Copy markdown files and attachments to public folder'
  inputs:
    script: |
      mkdir public 
      cp -R ALM/ SpecFlow/ public
      tree -a public

- task: CmdLine@2
  displayName: 'Compile markdown files'
  inputs:
    script: |
      for i in `find public -name "*.md" -type f`; do
        claat export "$i"
        echo "$i"
      done
      tree -a public
