variables:
  GOPATH: '$(system.defaultWorkingDirectory)/gopath' # Go workspace path
  GOBIN:  '$(GOPATH)/bin' # Go binaries path
trigger: none
pool:
  vmImage: 'ubuntu-latest'
steps:
- task: GoTool@0
  displayName: 'Use latest Go '
  inputs:
    version: '1.16.3'
    
- task: Go@0
  displayName: 'Get CLAAT'
  inputs:    
    command: 'custom'
    customCommand: 'install'
    arguments: 'github.com/googlecodelabs/tools/claat@latest'
    
- task: CmdLine@2
  displayName: 'Compile markdown files'
  inputs:
    script: |
      mkdir codelabs 
      cd codelabs
      for i in `find ../ALM ../SpecFlow -name "*.md" -type f`; do
        $(GOBIN)/claat export "$i"
        echo "$i"        
      done
      tree -a .

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(system.defaultWorkingDirectory)/codelabs'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'codelabs'
    publishLocation: 'Container'