trigger: none

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: GoTool@0
  displayName: 'Use latest Go '
  inputs:
    version: '1.16.3'

- task: Go@0
  displayName: 'Get CLAAT'
  inputs:
    command: 'get'
    arguments: 'github.com/googlecodelabs/tools/claat'
    
- task: CmdLine@2
  displayName: 'Copy lab files'
  inputs:
    script: |
      mkdir public 
      cp ALM/*.* public
      cp SpecFlow/*.* public
      ls public -a
      ls public/ALM -a
      ls public/SpecFlow -a
      ls public/ALM/.attachments -a
      ls public/SpecFlow/.attachments -a



