stages:
  - stage: Deploy
    displayName: "Deploy"
    pool:
      vmImage: "ubuntu-latest"
    jobs:
      - job: DeployJob
        displayName: "Deploy"

        steps:
          - checkout: self

          - download: current
            artifact: 'site'
            displayName: 'Download site'

          - task: AzureStaticWebApp@0
            inputs:
              output_location: '$(Pipeline.Workspace)/site'
              azure_static_web_apps_api_token: $(deployment_token)
