trigger:
  branches:
    include:
      - main
      
pr: none

pool:
  vmImage: "ubuntu-latest"

stages:
  - template: templates/include-build-stage.yml
  - template: templates/include-deploy-stage.yml
